version: '3'
services:

  azure-storage:
    image: azure-storage
    build: 
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "4000:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=videostreamtask
      - STORAGE_ACCESS_KEY=6/rXEcjw5QdaIAz/H2JlR7MPqot+0NSm/INIawZ8qYJS9uyhiFRhwGQu6UP9z0859pzeJO8ShUB++AStr8PmWw==
    restart: "no"

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"
